# Generated by Django 3.2 on 2025-07-17 22:50

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Укажите год выпуска', null=True, validators=[reviews.validators.year_validator], verbose_name='Год'),
        ),
    ]
