# Generated by Django 3.2 on 2025-07-19 19:32

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20250719_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(null=True, validators=[reviews.validators.score_validator]),
        ),
    ]
